import 'dart:io';

import 'package:playtorrio/models/subtitle/subtitle_model.dart';
import './providers/subdl_provider.dart';
import './providers/subtitlecat_provider.dart';
import './providers/wyzie_provider.dart';
import './providers/opensubtitles_provider.dart';
import './providers/stremio_subtitle_provider.dart';
import './subtitle_provider.dart';

class SubtitleService {
  static final SubtitleService _instance = SubtitleService._internal();
  factory SubtitleService() => _instance;
  SubtitleService._internal();

  final List<SubtitleProvider> _providers = [
    WyzieProvider(),
    SubtitleCatProvider(),
    OpenSubtitlesProvider(),
    SubdlProvider(),
    StremioSubtitleProvider(),
  ];

  /// Fetches subtitles from all registered providers concurrently.
  /// Groups the results by language.
  Future<List<SubtitleLanguageGroup>> fetchAllSubtitles(
    String movieName, {
    String? imdbId,
    int? season,
    int? episode,
    int? year,
  }) async {
    final futures = _providers.map((p) => p.search(
      movieName,
      imdbId: imdbId,
      season: season,
      episode: episode,
      year: year,
    ));
    
    // Wait for all providers to finish (or fail)
    final results = await Future.wait(futures.map((f) => f.catchError((_) => <SubtitleVariant>[])));
    
    final List<SubtitleVariant> allVariants = results.expand((x) => x).toList();
    
    if (allVariants.isEmpty) return [];

    // Group by language
    final Map<String, List<SubtitleVariant>> grouped = {};
    for (final variant in allVariants) {
      grouped.putIfAbsent(variant.language, () => []).add(variant);
    }

    // Sort languages alphabetically
    final sortedKeys = grouped.keys.toList()..sort((a, b) => a.compareTo(b));
    
    return sortedKeys.map((lang) {
      return SubtitleLanguageGroup(language: lang, variants: grouped[lang]!);
    }).toList();
  }

  /// Downloads and extracts the specific subtitle variant.
  Future<String?> downloadSubtitle(SubtitleVariant variant) async {
    SubtitleProvider? provider;
    try {
      provider = _providers.firstWhere((p) => p.name == variant.providerName);
    } catch (_) {
      // If variant was generated by an addon, use StremioSubtitleProvider
      try {
        provider = _providers.firstWhere((p) => p is StremioSubtitleProvider);
      } catch (_) {
        provider = _providers.first;
      }
    }
    return provider.download(variant);
  }

  /// Best-effort delete of a downloaded subtitle temp file (including synced
  /// copies). Called by the player slice on switch/dispose; never throws.
  Future<void> deleteSubtitleFile(String? path) async {
    if (path == null || path.isEmpty) return;
    try {
      final file = File(path);
      if (await file.exists()) await file.delete();
    } catch (_) {}
  }
}
